# Generated by Django 5.2.4 on 2025-07-25 13:51

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


content_type_global, created = ContentType.objects.get_or_create(app_label = 'users_upp', model = 'global')

def add_permissions(apps, schema_editor):

    Permission.objects.create(
        codename = 'can_manage_users',
        name = 'Can manage users',
        content_type = content_type_global
    )

    Permission.objects.create(
        codename = 'can_add_permissions_users',
        name = 'Can add permissions users',
        content_type = content_type_global
    )

    Permission.objects.create(
        codename = 'can_acces_users_list',
        name = 'can acces users list',
        content_type = content_type_global
    )

def rollback_permissions(apps, schema_editor):
     Permission.objects.filter(
        content_type = content_type_global,
        codename__in = ['can_manage_users','can_add_permissions_users','can_acces_users_list']

     ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(
            code = add_permissions,
            reverse_code = rollback_permissions
        ),
    ]
