# Generated by Django 5.2.4 on 2025-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_ID', models.AutoField(primary_key=True, serialize=False)),
                ('city_ID', models.IntegerField()),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
    ]
