# Generated by Django 5.2.4 on 2025-07-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'permissions': [('Can_administrate_lib', 'User can administrate the library'), ('Can_add_object', 'User can administrate DB')]},
        ),
    ]
