# Generated by Django 5.2.4 on 2025-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_district_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='district_images/'),
        ),
        migrations.AddField(
            model_name='district',
            name='is_admin_district',
            field=models.BooleanField(default=False),
        ),
    ]
